[project]
name = "graphpatch"
version = "0.2.3"
description = "graphpatch is a library for activation patching on PyTorch neural network models."
authors = [{ name = "Evan Lloyd", email = "evan.t.lloyd@gmail.com" }]
requires-python = ">=3.8.1, <3.13"
readme = "README.md"
license = "MIT"
keywords = [
    "mechanistic interpretability",
    "interpretability",
    "pytorch",
    "torch",
    "activation patch",
    "ablation",
    "transformer",
    "large language model",
    "llm",
]
classifiers = ["Development Status :: 4 - Beta"]
dependencies = [
    "torch>=2.4,<2.6 ; python_version >= '3.12'",
    "torch>=2.1,<2.6 ; python_version >= '3.11' and python_version < '3.12'",
    "torch>=2.0,<2.6 ; python_version >= '3.9' and python_version < '3.11'",
    "torch>=2.0,<2.5 ; python_version >= '3.8' and python_version < '3.9'",
    "numpy>=1.17,<1.25 ; python_version < '3.9'",
    "numpy>=1.17,<2.1 ; python_version >= '3.9' and python_version < '3.10'",
    "numpy>=1.17 ; python_version >= '3.10' and python_version < '3.12'",
    "numpy>=1.26 ; python_version >= '3.12'",
]

[project.optional-dependencies]
transformers = [
    "transformers>=4.28.0",
    "sentencepiece>=0.1.94",
    "accelerate>=0.15.0",
    "bitsandbytes>=0.35.4 ; sys_platform != 'darwin'",
]
transformer-lens = ["transformer-lens>=1.16.0"]

[project.urls]
Homepage = "https://www.graphpatch.dev"
Repository = "https://github.com/evan-lloyd/graphpatch"
Documentation = "https://graphpatch.readthedocs.io/en/latest/index.html"

[dependency-groups]
dev = [
    "ipykernel>=6.25.2,<7",
    "tuna>=0.5.11,<0.6",
    "jupyterlab>=4.0.7,<5",
    "ipywidgets>=8.1.1,<9",
    "tox>=4.11.3,<5",
    "sphobjinv>=2.3.1,<3",
]
testenv-lint = ["flake8>=6.1.0,<7"]
testenv-format = ["black[jupyter]>=23.10.1,<24", "isort>=5.12.0,<6"]
testenv-typecheck = ["mypy>=1.6.1,<2"]
testenv-test = [
    "pytest>=7.4.2,<8",
    "pytest-mock>=3.12.0,<4",
    "syrupy>=4.6.4,<5",
    "ipython>=8.12.3,<9",
    "pdbpp>=0.10.3,<0.11",
    "pytest-xdist>=3.5.0,<4",
    "pytest-env>=1.1.3,<2",
    #"pandas<2.1.0 ; python_version < '3.9'",
    #"pandas ; python_version >= '3.9'",
]
testenv-debug = ["xdot~=1.3", "graphviz>=0.20.3,<0.21", "objgraph>=3.6.1,<4"]
testenv-test-notebooks = ["nbmake>=1.4.6,<2"]
testenv-test-coverage = ["pytest-cov>=4.1.0,<5"]
testenv-docs = [
    "docutils>=0.21.2 ; python_version >= '3.12'",
    "furo>=2024.04.27; python_version>='3.12'",
    "sphinx>=8.0.0; python_version>='3.12'",
    "sphinx-autobuild>=2024.10.3 ; python_version >= '3.12'",
    "sphinx-markdown-builder>=0.6.7 ; python_version >= '3.12'",
]
torch-20 = ["torch"]

[tool.uv]
default-groups = ["dev"]
# conflicts = [[{ group = "testenv-docs" }, { group = "dev" }]]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu118"
url = "https://download.pytorch.org/whl/cu118"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[[tool.uv.index]]
name = "pytorch-rocm"
url = "https://download.pytorch.org/whl/rocm6.2"
explicit = true

[tool.uv.sources]
torch = [
    { url = "https://download.pytorch.org/whl/cpu/torch-2.5.0-cp312-none-macosx_11_0_arm64.whl", marker = "python_version >= '3.12' and python_version < '3.13' and sys_platform == 'darwin'" },
    { url = "https://download.pytorch.org/whl/cpu/torch-2.5.0-cp311-none-macosx_11_0_arm64.whl", marker = "python_version >= '3.11' and python_version < '3.12' and sys_platform == 'darwin'" },
    { url = "https://download.pytorch.org/whl/cpu/torch-2.5.0-cp310-none-macosx_11_0_arm64.whl", marker = "python_version >= '3.10' and python_version < '3.11' and sys_platform == 'darwin'" },
    { url = "https://download.pytorch.org/whl/cpu/torch-2.5.0-cp39-none-macosx_11_0_arm64.whl", marker = "python_version >= '3.9' and python_version < '3.10' and sys_platform == 'darwin'" },
    { url = "https://download.pytorch.org/whl/cu118/torch-2.5.0%2Bcu118-cp312-cp312-linux_x86_64.whl", marker = "python_version >= '3.12' and python_version < '3.13' and sys_platform == 'linux'" },
    { url = "https://download.pytorch.org/whl/cu118/torch-2.5.0%2Bcu118-cp311-cp311-linux_x86_64.whl", marker = "python_version >= '3.11' and python_version < '3.12' and sys_platform == 'linux'" },
    { url = "https://download.pytorch.org/whl/cu118/torch-2.5.0%2Bcu118-cp310-cp310-linux_x86_64.whl", marker = "python_version >= '3.10' and python_version < '3.11' and sys_platform == 'linux'" },
    { url = "https://download.pytorch.org/whl/cu118/torch-2.5.0%2Bcu118-cp39-cp39-linux_x86_64.whl", marker = "python_version >= '3.9' and python_version < '3.10' and sys_platform == 'linux'" },
]

[tool.hatch.build.targets.sdist]
include = ["graphpatch"]

[tool.hatch.build.targets.wheel]
include = ["graphpatch"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
